import { CheckResult, DocType, Fields } from "@/lib/types";

export function buildSummaryText(fields: Fields, docType: DocType, checks: CheckResult[]): string {
  const isLetter = docType === "letter";
  const nBlock = checks.filter((c) => c.status === "blocker").length;
  const nWarn = checks.filter((c) => c.status === "warning").length;
  const parts: string[] = [];
  if (nBlock) parts.push(`${nBlock} ${nBlock === 1 ? "hard conflict" : "hard conflicts"}`);
  if (nWarn) parts.push(`${nWarn} ${nWarn === 1 ? "warning" : "warnings"}`);
  const summaryCount = parts.length ? parts.join(" · ") : "No conflicts found";

  const lines = [
    `CPT check, ${fields.employer} (${summaryCount})`,
    `Document: ${isLetter ? "offer letter" : "job listing"}`,
    "",
  ];
  checks.forEach((c) => {
    lines.push(
      `[${c.status.toUpperCase()}] ${c.title}, ${isLetter ? "letter" : "listing"}: ${c.offerValue} / published rule: ${c.ruleValue}\n  ${c.nextStep}\n  Source: OIS, ${c.source.name}`,
    );
  });
  lines.push("", "Generated by Litmus. Not an eligibility decision, requesting OIS confirmation.");
  return lines.join("\n");
}
